name: SkyBlock
description: A powerful core for SkyBlock servers
author: GiantQuartz
website: twitter.com/GiantQuartz
main: room17\SkyBlock\SkyBlock
version: 4.0
api: 4.0.0

permissions:
  skyblock.interaction:
    description: Allows players to interact with an island regardless of whether they belong to it
    default: op
