name: SkyBlock
description: A powerful core for SkyBlock servers
author: dresnite
website: twitter.com/dresnite
main: room17\SkyBlock\SkyBlock
version: 4.0.2
api: 5.0.0

permissions:
  skyblock.interaction:
    description: Allows players to interact with an island regardless of whether they belong to it
    default: op
  skyblock.command.island:
    description: Allows players to use the island command
    default: true
