# This is the settings file of SkyBlock by @room17

# DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU ARE DOING
# The plugin uses this value to update your settings file when it is necessary
Version: 3

NewCustomChestContent:
  basic: []
  lost: []
  op: []
  palm: []
  shelly: []

# If you don't have set a specific chest content for a generator, it will be spawned with the following chest content.
# Each value of the list stands for an item, this is the required format to add a new item:
# [Item name], [Count = 1]
NewChestContent:
  - ["minecraft:bucket"]
  - ["minecraft:lava_bucket"]
  - ["minecraft:water_bucket"]
  - ["minecraft:ice"]
  - ["minecraft:melon_slice", 2]
  - ["minecraft:bone"]
  - ["minecraft:pumpkin_seeds"]
  - ["minecraft:cactus"]
  - ["minecraft:sugar_cane"]
  - ["minecraft:bread"]
  - ["minecraft:wheat"]
  - ["minecraft:leather_helmet"]
  - ["minecraft:leather_chestplate"]
  - ["minecraft:leather_leggings"]
  - ["minecraft:leather_boots"]

# The amount of slots an island will have in base of their island's category
# The category changes in base of how many blocks have been built on an island
SlotsByCategory:
  XS: 2
  S: 5
  M: 10
  L: 15
  XL: 20

# The amount of built blocks necessary to reach the next category
CategoryByBlocks:
  XS: 500
  S: 1000
  M: 5000
  L: 10000

# The amount of minutes a person has to wait to create another island, you can use it to prevent players from spamming
# island creation to slow down your server and/or to prevent them from getting the island chest unlimited times
CreationCooldownDuration: 20

# Should we save your players from dying into the void when they're in their islands?
CancelVoidDamage: true

# The commands that can't be used on the islands
BlockedCommands:
  - sethome
  - home

# The chat format of the messages sent through the private island chat
ChatFormat: "{BOLD}{YELLOW}{username} {GRAY}> {WHITE}{message}"